BattleField/config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :customers
  resources :classmates
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

BattleField/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

BattleField/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

BattleField/app/models/classmate.rb
class Classmate < ApplicationRecord
end

BattleField/app/models/customer.rb
class Customer < ApplicationRecord
end

BattleField/app/models/order.rb
class Order < ApplicationRecord
end

BattleField/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token, if: -> { controller_name == "sessions" && action_name == "create" }
end

BattleField/app/controllers/classmates_controller.rb
class ClassmatesController < InheritedResources::Base
    def get
      Loger.log("geting")
    end
  private
    
    def classmate_params
      params.require(:classmate).permit(:name, :age)
    end

end

BattleField/app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base

  private

    def customer_params
      params.require(:customer).permit(:name, :amount, :telephone)
    end

end

BattleField/app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  private

    def order_params
      params.require(:order).permit(:name, :good_name, :amount, :price)
    end

end

BattleField/app/helpers/application_helper.rb
module ApplicationHelper
end

BattleField/app/helpers/classmates_helper.rb
module ClassmatesHelper
end

BattleField/app/helpers/customers_helper.rb
module CustomersHelper
end

BattleField/app/helpers/orders_helper.rb
module OrdersHelper
end

BattleField/app/views/classmates/_form.html.erb
<%= form_with(model: classmate, local: true) do |form| %>
  <% if classmate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classmate.errors.count, "error") %> prohibited this classmate from being saved:</h2>

      <ul>
        <% classmate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BattleField/app/views/classmates/edit.html.erb
<h1>Editing Classmate</h1>

<%= render 'form', classmate: @classmate %>

<%= link_to 'Show', @classmate %> |
<%= link_to 'Back', classmates_path %>

BattleField/app/views/classmates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classmates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classmates.each do |classmate| %>
      <tr>
        <td><%= classmate.name %></td>
        <td><%= classmate.age %></td>
        <td><%= link_to 'Show', classmate %></td>
        <td><%= link_to 'Edit', edit_classmate_path(classmate) %></td>
        <td><%= link_to 'Destroy', classmate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classmate', new_classmate_path %>

BattleField/app/views/classmates/new.html.erb
<h1>New Classmate</h1>

<%= render 'form', classmate: @classmate %>

<%= link_to 'Back', classmates_path %>

BattleField/app/views/classmates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classmate.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @classmate.age %>
</p>

<%= link_to 'Edit', edit_classmate_path(@classmate) %> |
<%= link_to 'Back', classmates_path %>

BattleField/app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BattleField/app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

BattleField/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.amount %></td>
        <td><%= customer.telephone %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

BattleField/app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

BattleField/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @customer.amount %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @customer.telephone %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

BattleField/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Battlefield</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

BattleField/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :good_name %>
    <%= form.text_field :good_name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BattleField/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

BattleField/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Good name</th>
      <th>Amount</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.good_name %></td>
        <td><%= order.amount %></td>
        <td><%= order.price %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

BattleField/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

BattleField/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Good name:</strong>
  <%= @order.good_name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>